### ISSUE TITLE
Update description of TOOL1723 (BODCNVS-1955)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#206]
I'd like to do one of two things:

Either
1)Update L22/TOOL1723 to include all QSR-2000 models: QSR-2100, QSR-2150, QSR-2200
or
2) Create a new term for QSR-2200

http://www.biospherical.com/BSI%20PDFs/Brochures/QSR-2000.pdf - Documentation

**Comment by roswri** [comment]
Hi @rhudak2020 

I went with option 2, since the QSR-2000 and QSR-2150 models already exist in L22. The new term has been created and is queued for publication on the NVS - Biospherical Instruments QSR 2200 surface reference radiometer (http://vocab.nerc.ac.uk/collection/L22/current/TOOL2017/)  the link should go live early tomorrow morning
