### ISSUE TITLE
Update existing term (BODCNVS-1034)

### ISSUE THREAD

**Issue by rhudak2020** [nvs-vocabs/L22#79]
I would like to request that term L22/TOOL1117 be either updated to be a Seabird product as Satlantic was bought out several years ago. Or a new term be created for the Seabird HyperOCR with callouts for ICSA (air) and ICSW (water). Thanks in advance!

[HyperOCR_Datasheet.pdf](https://github.com/nvs-vocabs/L22/files/6436920/HyperOCR_Datasheet.pdf)

**Comment by danibodc** [comment]
Hi @rhudak2020 

Thanks for this, I have updated the description to outline that this was initially developed by Satlantic but is currently distributed by Sea_Bird since the companies combined in 2011. 

I also updated the preferred label to:
Sea-Bird {Satlantic} HyperOCR spectroradiometer series

And the alternative label to:
Sea-Bird Satlantic HyperOCR

This follows the convention used in https://vocab.nerc.ac.uk/collection/L22/current/TOOL1470/ which addresses a similar issue.

These changes will be live on the NVS from 0730 UTC tomorrow morning.

Thanks again!
